version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run: apt update
      - run: apt upgrade -y
      - run: apt install -y cmake make gcc g++ git
      - run: git submodule --init --recurive
      - run: mkdir build;cd build;cmake -DBUILD_TESTS=ON ..;make -j8;make test
